language: go
go:
  - "1.10.x"
go_import_path: github.com/titpetric/pendulum
cache:
  directories:
    - "front/node_modules"
env:
  - "PATH=/home/travis/gopath/bin:$PATH REPO_VERSION=$(git log -1 --format=%cd --date=unix) REPO_TAG=$(date -d @$REPO_VERSION +%Y.%m.%d.%H%M%S)"
before_install:
  - nvm install node
before_script:
  - go get github.com/tcnksm/ghr
  - go get github.com/jteeuwen/go-bindata/...
script:
  - ./build_all.sh
after_success:
  - ghr --username mreider --token $GITHUB_TOKEN --replace --prerelease --debug $REPO_TAG build/
